### PR TITLE
Current session top nav bar

### PR DESCRIPTION
**Pull request by ashequl93**
## Description
This PR contains the code for Top Nav Bar in Current Session Tab. By default, when the user goes into the current session tab, it will show the Menu tab. The user can tap on any tabs to go to the corresponding screen. 

## How to test
Pull this branch locally and go to the current session tab.
Screen Shot 2021-12-24 at 2 09 07 PM
Screen Shot 2021-12-24 at 2 09 45 PM
Screen Shot 2021-12-24 at 2 10 07 PM
Screen Shot 2021-12-24 at 2 10 25 PM

## Issue tracking
https://trello.com/c/LCeAQaMR

### CODE REVIEW

**Review by tm2838 — APPROVED** [review]
🙌  good stuff!

I noticed that the style for summary page is a little bit off, probably because I used absolute values for positioning (CSS...). Do you mind making these adjustment and see how it looks on your simulator?
1. change `height` in `GuestList.js` to 45%
2. in `CurrentSessionSummary.js`
- for `container`, remove `marginTop`
- for `title`, change `marginTop` to 5% and `height` to 10%

Also should we rename `CurrentSessionSummary.js` to `CurrentSessionSummary.screen.js` for consistency?

Thank you! (totally fine with changing those myself after this is merged!)

**Review by crystalsong2021 — APPROVED** [review]
nice.

**Comment by ashequl93** [comment]
> 🙌 good stuff!
> 
> I noticed that the style for summary page is a little bit off, probably because I used absolute values for positioning (CSS...). Do you mind making these adjustment and see how it looks on your simulator?
> 
> 1. change `height` in `GuestList.js` to 45%
> 2. in `CurrentSessionSummary.js`
> 
> * for `container`, remove `marginTop`
> * for `title`, change `marginTop` to 5% and `height` to 10%
> 
> Also should we rename `CurrentSessionSummary.js` to `CurrentSessionSummary.screen.js` for consistency?
> 
> Thank you! (totally fine with changing those myself after this is merged!)

**Comment by ashequl93** [comment]
Hi @tm2838 , I have made the changes as you suggested. In Android, it looks fine, but on iPhone simulators, it looks a bit off. 
Screen Shot 2021-12-24 at 2 57 30 PM
Screen Shot 2021-12-24 at 2 57 44 PM

**Pull request merged**
