### PR TITLE
Initial setup of biteshare app

### PR DESCRIPTION
**Pull request by ashequl93**
Hi, 
This is an initial Setup of our BiteShare app. Although we will start working from next week, an initial repo setup would be helpful for everyone to add new features to. It is not a rigid version by any means, feel free to request/add changes. Can you please make sure everyone can run this app into their local iOS and Android devices? 
How to run:
1. Install expo-cli `npm install -g expo-cli`
2. Clone this repo into your local machine
3. Go to the root folder by `cd biteshare`
4. Run `npm start` or `expo start`
5. You can run on real devices also, for that after running the command at point 4, scan the QR code. (You need to install the expo client app from the play store/app store)
6. To run in the iOS simulator, you need to install Xcode, and to run it on the android emulator, you need to install Android studio into your local machine.
Android:
Screen Shot 2021-12-15 at 8 19 26 PM
iPhone: 
Screen Shot 2021-12-15 at 8 18 50 PM

### CODE REVIEW

**Review by christinanate — CHANGES_REQUESTED** [review]
Change to HR linter

**Review by crystalsong2021 — CHANGES_REQUESTED** [review]
If you can change to HR Linter, that will be great. Thank you.

**Comment by ashequl93** [comment]
> Change to HR linter

Done

**Review by tm2838 — APPROVED** [review]
Could run the simulator and see the app! very cool 👍

**Review by crystalsong2021 — APPROVED** [review]
Thank you for setting up.

**Review by Josh-Kohl — APPROVED** [review]
Linter setup looks good.

**Review by JeremiahBerndt — APPROVED** [review]

**Review by christinanate — APPROVED** [review]

**Pull request merged**
